# Minimal configuration for Boxy
# Only the RIGHT ARM is used

simulation: true
verbose: true

freq_tf_update: 0.5

roi_frames:
  rightarm:
    Ta: "right_arm_flange_link"
    Tb: "triangle_right_arm_link"

joint_weights:
  triangle_base_joint: 20.0
  head_pan_joint:      0.1
  head_tilt_joint:     0.1

solver_config:
  max_iterations:     300
  max_cpu_time:        0.0
  sample_time:         0.004
  convergence_crit:    0.0001 #note: exponential notation only from YAML1.2
  regularization:      0.0001
  initialization_time: 3
  
init_joint_state:  
  right_arm_0_joint:    0.0
  right_arm_1_joint:   -0.5
  right_arm_2_joint:    0.0
  right_arm_3_joint:    1.0
  right_arm_4_joint:    0.0
  right_arm_5_joint:    0.0
  right_arm_6_joint:    0.0
  
  triangle_base_joint: -0.1
  head_pan_joint:       0.0
  head_tilt_joint:      0.0